export enum modalTestId {
  MODAL_CONTAINER = 'MODAL_CONTAINER',
  MODAL_TEXT = 'MODAL_TEXT',
  MODAL_TITLE = 'MODAL_TITLE',
  MODAL_CLOSE_BUTTON = 'MODAL_CLOSE_BUTTON',
  MODAL_CLOSE_ICON = 'MODAL_CLOSE_ICON',
}
