export enum buttonTestId {
  BUTTON_DEFAULT = 'BUTTON_DEFAULT',
  BUTTON_SECONDARY = 'BUTTON_SECONDARY',
  BUTTON_LOADING = 'BUTTON_LOADING',
  BUTTON_DISABLED = 'BUTTON_DISABLED',
  BUTTON_TITLE = 'BUTTON_TITLE',
}
